# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

spark.sql("USE CATALOG `masterdb_dev`")
spark.sql("USE SCHEMA `demo_db`")

# COMMAND ----------

display(spark.sql("SELECT * FROM samples.wanderbricks.users"))

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT * FROM masterdb_dev.demo_db.daily_sales_uk_2022
